# Generated by Django 6.0.7 on 2026-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('sujet', models.CharField(max_length=200, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('image', models.ImageField(upload_to='produits/', verbose_name='image')),
                ('couleurs', models.CharField(choices=[('noir', 'Noir'), ('blanc', 'Blanc'), ('rouge', 'Rouge'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('rose', 'Rose'), ('beige', 'Beige'), ('chocolat', 'Chocolat')], default='noir', max_length=20, verbose_name='couleur')),
                ('tailles', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=5, verbose_name='taille')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
